name: flutter_scroll_shadow_example
description: A demonstration of the ScrollShadow widget for a scrollable child.
version: 1.2.0
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_scroll_shadow:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true