name: flutter_scroll_shadow
description: ScrollShadow adds shadows to a scrollable child. Supports
  ScrollController and vertical or horizontal orientation.
version: 1.2.5
repository: https://github.com/rickypid/flutter_scroll_shadow
issue_tracker: https://github.com/rickypid/flutter_scroll_shadow/issues
homepage: https://github.com/rickypid/flutter_scroll_shadow
documentation: https://github.com/rickypid/flutter_scroll_shadow#readme

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  collection: ^1.17.2

flutter: null